import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../common/Navbar"; // <-- import your navbar
import Footer from "@/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <Navbar/>  {/* 👈 Navbar appears on all pages */}

        <main>
          {children}
        </main>
     <Footer/>
      </body>
    </html>
  );
}
